# Generated by Django 6.0.4 on 2026-04-14 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('availability', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityexception',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availabilityrecurring',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='availabilityexception',
            index=models.Index(fields=['user', 'date'], name='availabilit_user_id_6a5bf6_idx'),
        ),
    ]
