# Generated by Django 6.0.4 on 2026-04-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityexception',
            name='is_full_day',
            field=models.BooleanField(default=False),
        ),
    ]
