# Generated by Django 6.0.4 on 2026-04-14 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userlocation',
            constraint=models.UniqueConstraint(fields=('user', 'location'), name='unique_user_location'),
        ),
    ]
