# Generated by Django 6.0.4 on 2026-04-14 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userweeklystats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userweeklystats',
            constraint=models.UniqueConstraint(fields=('user', 'week_start'), name='unique_user_week'),
        ),
    ]
