# Generated by Django 6.0.4 on 2026-04-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
